<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="8" ignored="0" total="10" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="126857" started-at="2018-11-13T16:18:30Z" finished-at="2018-11-13T16:20:36Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="126857" started-at="2018-11-13T16:18:30Z" finished-at="2018-11-13T16:20:36Z">
      <class name="leanTesting.TC1_LeanTestingRegisterExcelData">
        <test-method status="FAIL" signature="LeanTestingRegister(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:leanTesting.TC1_LeanTestingRegisterExcelData@1e88b3c]" name="LeanTestingRegister" duration-ms="12611" started-at="2018-11-13T16:18:31Z" data-provider="registerData" finished-at="2018-11-13T16:18:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[AlertVata1@mail.ru]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Abram745228]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[SSS-234-ttt]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at leanTesting.TC1_LeanTestingRegisterExcelData.LeanTestingRegister(TC1_LeanTestingRegisterExcelData.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LeanTestingRegister -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:leanTesting.TC1_LeanTestingRegisterExcelData@1e88b3c]" name="tearDown" is-config="true" duration-ms="215" started-at="2018-11-13T16:18:43Z" finished-at="2018-11-13T16:18:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="LeanTestingRegister(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:leanTesting.TC1_LeanTestingRegisterExcelData@1e88b3c]" name="LeanTestingRegister" duration-ms="11681" started-at="2018-11-13T16:18:43Z" data-provider="registerData" finished-at="2018-11-13T16:18:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[alertvata@mailru]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[More15Symbols1111]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[More20SymbolsRiRiRiRi]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at leanTesting.TC1_LeanTestingRegisterExcelData.LeanTestingRegister(TC1_LeanTestingRegisterExcelData.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LeanTestingRegister -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:leanTesting.TC1_LeanTestingRegisterExcelData@1e88b3c]" name="tearDown" is-config="true" duration-ms="2130" started-at="2018-11-13T16:18:55Z" finished-at="2018-11-13T16:18:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="LeanTestingRegister(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:leanTesting.TC1_LeanTestingRegisterExcelData@1e88b3c]" name="LeanTestingRegister" duration-ms="10910" started-at="2018-11-13T16:18:57Z" data-provider="registerData" finished-at="2018-11-13T16:19:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[alertvataAmail.ru]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[4Sls]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[5Sbls]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at leanTesting.TC1_LeanTestingRegisterExcelData.LeanTestingRegister(TC1_LeanTestingRegisterExcelData.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LeanTestingRegister -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:leanTesting.TC1_LeanTestingRegisterExcelData@1e88b3c]" name="tearDown" is-config="true" duration-ms="236" started-at="2018-11-13T16:19:08Z" finished-at="2018-11-13T16:19:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="LeanTestingRegister(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:leanTesting.TC1_LeanTestingRegisterExcelData@1e88b3c]" name="LeanTestingRegister" duration-ms="10801" started-at="2018-11-13T16:19:08Z" data-provider="registerData" finished-at="2018-11-13T16:19:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Alert-Vata@mail,ru]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Abram756]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[#11_22@S44%]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at leanTesting.TC1_LeanTestingRegisterExcelData.LeanTestingRegister(TC1_LeanTestingRegisterExcelData.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LeanTestingRegister -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:leanTesting.TC1_LeanTestingRegisterExcelData@1e88b3c]" name="tearDown" is-config="true" duration-ms="207" started-at="2018-11-13T16:19:19Z" finished-at="2018-11-13T16:19:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="LeanTestingRegister(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:leanTesting.TC1_LeanTestingRegisterExcelData@1e88b3c]" name="LeanTestingRegister" duration-ms="12050" started-at="2018-11-13T16:19:19Z" data-provider="registerData" finished-at="2018-11-13T16:19:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Alert_Vata1@mail.ru]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Alert_Vata1@mail.ru]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[AsD-22-34]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LeanTestingRegister -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:leanTesting.TC1_LeanTestingRegisterExcelData@1e88b3c]" name="tearDown" is-config="true" duration-ms="223" started-at="2018-11-13T16:19:31Z" finished-at="2018-11-13T16:19:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="LeanTestingRegister(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:leanTesting.TC1_LeanTestingRegisterExcelData@1e88b3c]" name="LeanTestingRegister" duration-ms="12250" started-at="2018-11-13T16:19:32Z" data-provider="registerData" finished-at="2018-11-13T16:19:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test1@mail.ru]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test1@mail.ru]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Test1@mail.ru]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LeanTestingRegister -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:leanTesting.TC1_LeanTestingRegisterExcelData@1e88b3c]" name="tearDown" is-config="true" duration-ms="231" started-at="2018-11-13T16:19:44Z" finished-at="2018-11-13T16:19:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="LeanTestingRegister(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:leanTesting.TC1_LeanTestingRegisterExcelData@1e88b3c]" name="LeanTestingRegister" duration-ms="12033" started-at="2018-11-13T16:19:44Z" data-provider="registerData" finished-at="2018-11-13T16:19:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test2@mailru]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[%%%%#####]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[fgjdfkgrt]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at leanTesting.TC1_LeanTestingRegisterExcelData.LeanTestingRegister(TC1_LeanTestingRegisterExcelData.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LeanTestingRegister -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:leanTesting.TC1_LeanTestingRegisterExcelData@1e88b3c]" name="tearDown" is-config="true" duration-ms="2197" started-at="2018-11-13T16:19:56Z" finished-at="2018-11-13T16:19:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="LeanTestingRegister(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:leanTesting.TC1_LeanTestingRegisterExcelData@1e88b3c]" name="LeanTestingRegister" duration-ms="11555" started-at="2018-11-13T16:19:58Z" data-provider="registerData" finished-at="2018-11-13T16:20:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test3@mайл.кг]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Иван]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[1234567]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at leanTesting.TC1_LeanTestingRegisterExcelData.LeanTestingRegister(TC1_LeanTestingRegisterExcelData.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LeanTestingRegister -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:leanTesting.TC1_LeanTestingRegisterExcelData@1e88b3c]" name="tearDown" is-config="true" duration-ms="230" started-at="2018-11-13T16:20:10Z" finished-at="2018-11-13T16:20:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="LeanTestingRegister(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:leanTesting.TC1_LeanTestingRegisterExcelData@1e88b3c]" name="LeanTestingRegister" duration-ms="11346" started-at="2018-11-13T16:20:10Z" data-provider="registerData" finished-at="2018-11-13T16:20:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin@mail.ru]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at leanTesting.TC1_LeanTestingRegisterExcelData.LeanTestingRegister(TC1_LeanTestingRegisterExcelData.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LeanTestingRegister -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:leanTesting.TC1_LeanTestingRegisterExcelData@1e88b3c]" name="tearDown" is-config="true" duration-ms="2099" started-at="2018-11-13T16:20:22Z" finished-at="2018-11-13T16:20:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="LeanTestingRegister(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:leanTesting.TC1_LeanTestingRegisterExcelData@1e88b3c]" name="LeanTestingRegister" duration-ms="10611" started-at="2018-11-13T16:20:24Z" data-provider="registerData" finished-at="2018-11-13T16:20:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test4amail.ru]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Login]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Password]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at leanTesting.TC1_LeanTestingRegisterExcelData.LeanTestingRegister(TC1_LeanTestingRegisterExcelData.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LeanTestingRegister -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:leanTesting.TC1_LeanTestingRegisterExcelData@1e88b3c]" name="tearDown" is-config="true" duration-ms="2105" started-at="2018-11-13T16:20:34Z" finished-at="2018-11-13T16:20:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- leanTesting.TC1_LeanTestingRegisterExcelData -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
